"""V4 canonical data intake components."""

from .fact_envelope import (
    AvailabilityStatus,
    CanonicalFactEnvelope,
    CanonicalFactObservation,
    CanonicalFactStore,
    CanonicalMatchReference,
    FactConflictEvidence,
    FactEnvelopeValidationError,
    FactIntakeResult,
)
from .match_identity import (
    CanonicalMatchIdentityEnvelope,
    CanonicalMatchIdentityStore,
    IdentityIntakeResult,
    MatchObservation,
    resolve_f_drive_output_path,
)
from .time_lineage import (
    AvailabilityTimeBasis,
    TimeGateResult,
    TimeGateStatus,
    TimeLineageDecision,
    TimeLineageInput,
    TimeLineageStore,
    TimeLineageValidationError,
)
from .orchestrator import (
    CanonicalIntakeOrchestrator,
    IntakeDeliveryRecord,
    IntakeOutcome,
    IntakeResult,
    OrchestratorValidationError,
)
from .official_odds import (
    MarketAvailabilityStatus,
    OfficialOddsIntakeResult,
    OfficialOddsObservation,
    OfficialOddsSnapshot,
    OfficialOddsSnapshotStore,
    OfficialOddsValidationError,
    SnapshotKind,
)
from .official_screenshot import (
    OfficialScreenshotEvidence,
    OfficialScreenshotEvidenceStore,
    OfficialScreenshotObservation,
    ScreenshotIntakeResult,
    ScreenshotVerificationState,
    ScreenshotValidationError,
)
from .official_availability import (
    AvailabilityGateOutcome,
    AvailabilityGateResult,
    AvailabilityGateValidationError,
    MarketAvailabilityDecision,
    MarketGateStatus,
    OfficialMarketAvailabilityGate,
)

__all__ = [
    "AvailabilityStatus",
    "CanonicalFactEnvelope",
    "CanonicalFactObservation",
    "CanonicalFactStore",
    "CanonicalMatchIdentityEnvelope",
    "CanonicalMatchIdentityStore",
    "CanonicalMatchReference",
    "FactConflictEvidence",
    "FactEnvelopeValidationError",
    "IdentityIntakeResult",
    "MatchObservation",
    "FactIntakeResult",
    "AvailabilityTimeBasis",
    "TimeGateResult",
    "TimeGateStatus",
    "TimeLineageDecision",
    "TimeLineageInput",
    "TimeLineageStore",
    "TimeLineageValidationError",
    "CanonicalIntakeOrchestrator",
    "IntakeDeliveryRecord",
    "IntakeOutcome",
    "IntakeResult",
    "OrchestratorValidationError",
    "MarketAvailabilityStatus",
    "OfficialOddsIntakeResult",
    "OfficialOddsObservation",
    "OfficialOddsSnapshot",
    "OfficialOddsSnapshotStore",
    "OfficialOddsValidationError",
    "SnapshotKind",
    "OfficialScreenshotEvidence",
    "OfficialScreenshotEvidenceStore",
    "OfficialScreenshotObservation",
    "ScreenshotIntakeResult",
    "ScreenshotVerificationState",
    "ScreenshotValidationError",
    "AvailabilityGateOutcome",
    "AvailabilityGateResult",
    "AvailabilityGateValidationError",
    "MarketAvailabilityDecision",
    "MarketGateStatus",
    "OfficialMarketAvailabilityGate",
    "resolve_f_drive_output_path",
]
