"""V4 canonical data intake components."""

from .fact_envelope import (
    AvailabilityStatus,
    CanonicalFactEnvelope,
    CanonicalFactObservation,
    CanonicalFactStore,
    CanonicalMatchReference,
    FactConflictEvidence,
    FactEnvelopeValidationError,
    FactIntakeResult,
)
from .match_identity import (
    CanonicalMatchIdentityEnvelope,
    CanonicalMatchIdentityStore,
    IdentityIntakeResult,
    MatchObservation,
    resolve_f_drive_output_path,
)
from .time_lineage import (
    AvailabilityTimeBasis,
    TimeGateResult,
    TimeGateStatus,
    TimeLineageDecision,
    TimeLineageInput,
    TimeLineageStore,
    TimeLineageValidationError,
)
from .orchestrator import (
    CanonicalIntakeOrchestrator,
    IntakeDeliveryRecord,
    IntakeOutcome,
    IntakeResult,
    OrchestratorValidationError,
)
from .official_odds import (
    MarketAvailabilityStatus,
    OfficialOddsIntakeResult,
    OfficialOddsObservation,
    OfficialOddsSnapshot,
    OfficialOddsSnapshotStore,
    OfficialOddsValidationError,
    SnapshotKind,
)
from .official_screenshot import (
    OfficialScreenshotEvidence,
    OfficialScreenshotEvidenceStore,
    OfficialScreenshotObservation,
    ScreenshotIntakeResult,
    ScreenshotVerificationState,
    ScreenshotValidationError,
)
from .official_availability import (
    AvailabilityGateOutcome,
    AvailabilityGateResult,
    AvailabilityGateValidationError,
    MarketAvailabilityDecision,
    MarketGateStatus,
    OfficialMarketAvailabilityGate,
)
from .official_ledger import (
    LedgerAction,
    OddsLedgerRequest,
    OddsLedgerResult,
    OddsProvenanceLedgerEntry,
    OfficialOddsLedgerValidationError,
    OfficialOddsProvenanceLedger,
)
from .external_market import (
    AsianHandicapIntake,
    ExternalConflictEvidence,
    ExternalAsianHandicapAdapter,
    ExternalEuropean1X2Adapter,
    ExternalMarket,
    ExternalMarketIntakeResult,
    ExternalMarketObservation,
    ExternalMarketSnapshot,
    ExternalMarketSnapshotStore,
    ExternalMarketStatus,
    ExternalMarketValidationError,
    ExternalOUAdapter,
    European1X2Intake,
    OverUnderIntake,
)
from .external_time_normalization import (
    ExternalSourceTimeNormalization,
    ExternalSourceTimeNormalizer,
    NormalizedExternalSnapshotRef,
    NormalizedExternalSnapshotSet,
    SourceTimeNormalizationError,
    SourceTimeNormalizationResult,
)
from .team_context import (
    AvailabilityContextObservation,
    AvailabilityContextRecord,
    AvailabilityContextResult,
    AvailabilityContextStore,
    CONTEXT_STATES,
    ContextValue,
    LINEUP_STATES,
    LineupCoachTacticalObservation,
    LineupCoachTacticalRecord,
    LineupCoachTacticalResult,
    LineupCoachTacticalStore,
    OPERATIONAL_CONTEXT_FIELDS,
    OPERATIONAL_CONTEXT_STATES,
    OperationalContextItem,
    OperationalContextObservation,
    OperationalContextRecord,
    OperationalContextResult,
    OperationalContextStore,
    StartingXIContext,
    TeamContextIdentityLinker,
    TeamContextValidationError,
    TeamIdentityConflict,
    TeamIdentityLink,
    TeamIdentityLinkObservation,
    TeamIdentityLinkResult,
    TeamSide,
    TypedFactCollection,
)
from .evidence_graph import (
    ContradictionState,
    EvidenceConfidence,
    EvidenceGraphStore,
    EvidenceGraphValidationError,
    EvidenceIntakeResult,
    EvidenceItem,
    EvidenceRelation,
    VerificationState,
)
from .source_conflict import (
    ConflictResolutionRecord,
    EvidenceQualityResult,
    FreshnessState,
    SourceConflictResolver,
    SourceQualityAssessment,
    SourceQualityBand,
)
from .feature_bundle import (
    CONTRACT_VERSION as FEATURE_BUNDLE_CONTRACT_VERSION,
    FEATURE_CATEGORIES,
    FeatureBundle,
    FeatureBundleResult,
    FeatureBundleStore,
    FeatureBundleValidationError,
    FeatureQuality,
    FeatureRecord,
    FeatureSchema,
    FeatureSchemaRegistry,
    FeatureState,
)
from .feature_snapshot import (
    CONTRACT_VERSION as FEATURE_SNAPSHOT_CONTRACT_VERSION,
    HASH_PROFILE as FEATURE_SNAPSHOT_HASH_PROFILE,
    VOLATILE_FIELDS as FEATURE_SNAPSHOT_VOLATILE_FIELDS,
    FeatureSnapshotHasher,
    FeatureSnapshotResult,
    FeatureSnapshotValidationError,
)
from .feature_assembly import (
    CONTRACT_VERSION as FEATURE_ASSEMBLY_CONTRACT_VERSION,
    SOURCE_KINDS,
    FeatureAssemblyResult,
    FeatureAssemblyStore,
    FeatureAssemblyValidationError,
    SchemaAdapter,
    SchemaAdapterRegistry,
    VersionedSourceObject,
)
from .statistical_strength import (
    CONFIG_VERSION as STATISTICAL_STRENGTH_CONFIG_VERSION,
    FEATURE_BUNDLE_CONTRACT_VERSION as STATISTICAL_FEATURE_BUNDLE_CONTRACT_VERSION,
    HISTORICAL_CONTRACT_VERSION as STATISTICAL_HISTORICAL_CONTRACT_VERSION,
    AttackDefenceHomeAdvantageEngine,
    AttackDefenceHomeAdvantageResult,
    DynamicTeamRatingEngine,
    FeatureQuality as StatisticalFeatureQuality,
    HistoricalAvailability,
    HistoricalInputManifest,
    HistoricalObservation,
    OpponentFormLeagueResult,
    OpponentFormLeagueStrengthEngine,
    StatisticalFeature,
    StatisticalFeatureState,
    StatisticalFeatureStore,
    StatisticalStrengthConfig,
    StatisticalStrengthValidationError,
    verify_feature_hash,
)
from .football_intelligence_governance import (
    CONFIG_PATH as FOOTBALL_INTELLIGENCE_CONFIG_PATH,
    CONFIG_VERSION as FOOTBALL_INTELLIGENCE_CONFIG_VERSION,
    CONTEXT_INTEGRATION_CONTRACT_VERSION,
    FEATURE_CONTRACT_VERSION as FOOTBALL_INTELLIGENCE_FEATURE_CONTRACT_VERSION,
    FootballIntelligenceGovernanceError,
    calculate_governance_hash,
    load_approved_config,
    validate_approved_config,
    validate_pre_freeze_artifact,
)
from .football_intelligence import (
    ARTIFACT_KIND as FOOTBALL_INTELLIGENCE_ARTIFACT_KIND,
    GENERATOR_VERSION as FOOTBALL_INTELLIGENCE_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as FOOTBALL_INTELLIGENCE_MAPPING_REGISTRY_VERSION,
    TEAM_CONTEXT_CONTRACT_VERSION as FOOTBALL_INTELLIGENCE_TEAM_CONTEXT_CONTRACT_VERSION,
    FootballIntelligenceArtifact,
    FootballIntelligenceEngine,
    FootballIntelligenceFeature,
    FootballIntelligenceStore,
    FootballIntelligenceValidationError,
)
from .context_feature_integration import (
    CONTRACT_VERSION as FOOTBALL_CONTEXT_INTEGRATION_CONTRACT_VERSION,
    GENERATOR_VERSION as FOOTBALL_CONTEXT_INTEGRATION_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as FOOTBALL_CONTEXT_INTEGRATION_MAPPING_REGISTRY_VERSION,
    ContextFeatureIntegrationArtifact,
    ContextFeatureIntegrationEngine,
    ContextFeatureIntegrationStore,
    ContextFeatureIntegrationValidationError,
)
from .market_intelligence import (
    ARTIFACT_KIND as MARKET_INTELLIGENCE_ARTIFACT_KIND,
    CONFIG_VERSION as MARKET_INTELLIGENCE_CONFIG_VERSION,
    CONTRACT_VERSION as MARKET_INTELLIGENCE_FEATURE_CONTRACT_VERSION,
    GENERATOR_VERSION as MARKET_INTELLIGENCE_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as MARKET_INTELLIGENCE_MAPPING_REGISTRY_VERSION,
    MarketIntelligenceArtifact,
    MarketIntelligenceEngine,
    MarketIntelligenceResult,
    MarketIntelligenceStore,
    MarketIntelligenceValidationError,
)
from .market_movement import (
    ARTIFACT_KIND as MARKET_MOVEMENT_ARTIFACT_KIND,
    CONFIG_VERSION as MARKET_MOVEMENT_CONFIG_VERSION,
    CONTRACT_VERSION as MARKET_MOVEMENT_CONTRACT_VERSION,
    GENERATOR_VERSION as MARKET_MOVEMENT_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as MARKET_MOVEMENT_MAPPING_REGISTRY_VERSION,
    MarketMovementArtifact,
    MarketMovementEngine,
    MarketMovementResult,
    MarketMovementStore,
    MarketMovementValidationError,
)
from .market_risk_interpretation import (
    ARTIFACT_KIND as MARKET_RISK_INTERPRETATION_ARTIFACT_KIND,
    CONFIG_VERSION as MARKET_RISK_INTERPRETATION_CONFIG_VERSION,
    CONTRACT_VERSION as MARKET_RISK_INTERPRETATION_CONTRACT_VERSION,
    GENERATOR_VERSION as MARKET_RISK_INTERPRETATION_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as MARKET_RISK_INTERPRETATION_MAPPING_REGISTRY_VERSION,
    MarketRiskInterpretationArtifact,
    MarketRiskInterpretationEngine,
    MarketRiskInterpretationResult,
    MarketRiskInterpretationStore,
    MarketRiskInterpretationValidationError,
)
from .tactical_league_profile import (
    ARTIFACT_KIND as TACTICAL_LEAGUE_PROFILE_ARTIFACT_KIND,
    CONTRACT_VERSION as TACTICAL_LEAGUE_PROFILE_CONTRACT_VERSION,
    GENERATOR_VERSION as TACTICAL_LEAGUE_PROFILE_GENERATOR_VERSION,
    MAPPING_REGISTRY_VERSION as TACTICAL_LEAGUE_PROFILE_MAPPING_REGISTRY_VERSION,
    TacticalLeagueProfileArtifact,
    TacticalLeagueProfileEngine,
    TacticalLeagueProfileStore,
    TacticalLeagueProfileValidationError,
)

__all__ = [
    "AvailabilityStatus",
    "CanonicalFactEnvelope",
    "CanonicalFactObservation",
    "CanonicalFactStore",
    "CanonicalMatchIdentityEnvelope",
    "CanonicalMatchIdentityStore",
    "CanonicalMatchReference",
    "FactConflictEvidence",
    "FactEnvelopeValidationError",
    "IdentityIntakeResult",
    "MatchObservation",
    "FactIntakeResult",
    "AvailabilityTimeBasis",
    "TimeGateResult",
    "TimeGateStatus",
    "TimeLineageDecision",
    "TimeLineageInput",
    "TimeLineageStore",
    "TimeLineageValidationError",
    "CanonicalIntakeOrchestrator",
    "IntakeDeliveryRecord",
    "IntakeOutcome",
    "IntakeResult",
    "OrchestratorValidationError",
    "MarketAvailabilityStatus",
    "OfficialOddsIntakeResult",
    "OfficialOddsObservation",
    "OfficialOddsSnapshot",
    "OfficialOddsSnapshotStore",
    "OfficialOddsValidationError",
    "SnapshotKind",
    "OfficialScreenshotEvidence",
    "OfficialScreenshotEvidenceStore",
    "OfficialScreenshotObservation",
    "ScreenshotIntakeResult",
    "ScreenshotVerificationState",
    "ScreenshotValidationError",
    "AvailabilityGateOutcome",
    "AvailabilityGateResult",
    "AvailabilityGateValidationError",
    "MarketAvailabilityDecision",
    "MarketGateStatus",
    "OfficialMarketAvailabilityGate",
    "LedgerAction",
    "OddsLedgerRequest",
    "OddsLedgerResult",
    "OddsProvenanceLedgerEntry",
    "OfficialOddsLedgerValidationError",
    "OfficialOddsProvenanceLedger",
    "ExternalMarket",
    "ExternalMarketStatus",
    "ExternalMarketValidationError",
    "ExternalConflictEvidence",
    "ExternalMarketObservation",
    "ExternalMarketSnapshot",
    "ExternalMarketIntakeResult",
    "ExternalMarketSnapshotStore",
    "ExternalEuropean1X2Adapter",
    "European1X2Intake",
    "ExternalAsianHandicapAdapter",
    "AsianHandicapIntake",
    "ExternalOUAdapter",
    "OverUnderIntake",
    "ExternalSourceTimeNormalizer",
    "ExternalSourceTimeNormalization",
    "NormalizedExternalSnapshotRef",
    "NormalizedExternalSnapshotSet",
    "SourceTimeNormalizationError",
    "SourceTimeNormalizationResult",
    "AvailabilityContextObservation",
    "AvailabilityContextRecord",
    "AvailabilityContextResult",
    "AvailabilityContextStore",
    "CONTEXT_STATES",
    "ContextValue",
    "LINEUP_STATES",
    "LineupCoachTacticalObservation",
    "LineupCoachTacticalRecord",
    "LineupCoachTacticalResult",
    "LineupCoachTacticalStore",
    "OPERATIONAL_CONTEXT_FIELDS",
    "OPERATIONAL_CONTEXT_STATES",
    "OperationalContextItem",
    "OperationalContextObservation",
    "OperationalContextRecord",
    "OperationalContextResult",
    "OperationalContextStore",
    "StartingXIContext",
    "TeamContextIdentityLinker",
    "TeamContextValidationError",
    "TeamIdentityConflict",
    "TeamIdentityLink",
    "TeamIdentityLinkObservation",
    "TeamIdentityLinkResult",
    "TeamSide",
    "TypedFactCollection",
    "ContradictionState",
    "EvidenceConfidence",
    "EvidenceGraphStore",
    "EvidenceGraphValidationError",
    "EvidenceIntakeResult",
    "EvidenceItem",
    "EvidenceRelation",
    "VerificationState",
    "ConflictResolutionRecord",
    "EvidenceQualityResult",
    "FreshnessState",
    "SourceConflictResolver",
    "SourceQualityAssessment",
    "SourceQualityBand",
    "FEATURE_BUNDLE_CONTRACT_VERSION",
    "FEATURE_CATEGORIES",
    "FeatureBundle",
    "FeatureBundleResult",
    "FeatureBundleStore",
    "FeatureBundleValidationError",
    "FeatureQuality",
    "FeatureRecord",
    "FeatureSchema",
    "FeatureSchemaRegistry",
    "FeatureState",
    "FEATURE_SNAPSHOT_CONTRACT_VERSION",
    "FEATURE_SNAPSHOT_HASH_PROFILE",
    "FEATURE_SNAPSHOT_VOLATILE_FIELDS",
    "FeatureSnapshotHasher",
    "FeatureSnapshotResult",
    "FeatureSnapshotValidationError",
    "FEATURE_ASSEMBLY_CONTRACT_VERSION",
    "SOURCE_KINDS",
    "FeatureAssemblyResult",
    "FeatureAssemblyStore",
    "FeatureAssemblyValidationError",
    "SchemaAdapter",
    "SchemaAdapterRegistry",
    "VersionedSourceObject",
    "resolve_f_drive_output_path",
    "STATISTICAL_STRENGTH_CONFIG_VERSION",
    "STATISTICAL_FEATURE_BUNDLE_CONTRACT_VERSION",
    "STATISTICAL_HISTORICAL_CONTRACT_VERSION",
    "AttackDefenceHomeAdvantageEngine",
    "AttackDefenceHomeAdvantageResult",
    "DynamicTeamRatingEngine",
    "StatisticalFeatureQuality",
    "HistoricalAvailability",
    "HistoricalInputManifest",
    "HistoricalObservation",
    "OpponentFormLeagueResult",
    "OpponentFormLeagueStrengthEngine",
    "StatisticalFeature",
    "StatisticalFeatureState",
    "StatisticalFeatureStore",
    "StatisticalStrengthConfig",
    "StatisticalStrengthValidationError",
    "verify_feature_hash",
    "FOOTBALL_INTELLIGENCE_CONFIG_PATH",
    "FOOTBALL_INTELLIGENCE_CONFIG_VERSION",
    "CONTEXT_INTEGRATION_CONTRACT_VERSION",
    "FOOTBALL_INTELLIGENCE_FEATURE_CONTRACT_VERSION",
    "FootballIntelligenceGovernanceError",
    "calculate_governance_hash",
    "load_approved_config",
    "validate_approved_config",
    "validate_pre_freeze_artifact",
    "FOOTBALL_INTELLIGENCE_ARTIFACT_KIND",
    "FOOTBALL_INTELLIGENCE_GENERATOR_VERSION",
    "FOOTBALL_INTELLIGENCE_MAPPING_REGISTRY_VERSION",
    "FOOTBALL_INTELLIGENCE_TEAM_CONTEXT_CONTRACT_VERSION",
    "FootballIntelligenceArtifact",
    "FootballIntelligenceEngine",
    "FootballIntelligenceFeature",
    "FootballIntelligenceStore",
    "FootballIntelligenceValidationError",
    "FOOTBALL_CONTEXT_INTEGRATION_CONTRACT_VERSION",
    "FOOTBALL_CONTEXT_INTEGRATION_GENERATOR_VERSION",
    "FOOTBALL_CONTEXT_INTEGRATION_MAPPING_REGISTRY_VERSION",
    "ContextFeatureIntegrationArtifact",
    "ContextFeatureIntegrationEngine",
    "ContextFeatureIntegrationStore",
    "ContextFeatureIntegrationValidationError",
    "MARKET_INTELLIGENCE_ARTIFACT_KIND",
    "MARKET_INTELLIGENCE_CONFIG_VERSION",
    "MARKET_INTELLIGENCE_FEATURE_CONTRACT_VERSION",
    "MARKET_INTELLIGENCE_GENERATOR_VERSION",
    "MARKET_INTELLIGENCE_MAPPING_REGISTRY_VERSION",
    "MarketIntelligenceArtifact",
    "MarketIntelligenceEngine",
    "MarketIntelligenceResult",
    "MarketIntelligenceStore",
    "MarketIntelligenceValidationError",
    "MARKET_MOVEMENT_ARTIFACT_KIND",
    "MARKET_MOVEMENT_CONFIG_VERSION",
    "MARKET_MOVEMENT_CONTRACT_VERSION",
    "MARKET_MOVEMENT_GENERATOR_VERSION",
    "MARKET_MOVEMENT_MAPPING_REGISTRY_VERSION",
    "MarketMovementArtifact",
    "MarketMovementEngine",
    "MarketMovementResult",
    "MarketMovementStore",
    "MarketMovementValidationError",
    "MARKET_RISK_INTERPRETATION_ARTIFACT_KIND",
    "MARKET_RISK_INTERPRETATION_CONFIG_VERSION",
    "MARKET_RISK_INTERPRETATION_CONTRACT_VERSION",
    "MARKET_RISK_INTERPRETATION_GENERATOR_VERSION",
    "MARKET_RISK_INTERPRETATION_MAPPING_REGISTRY_VERSION",
    "MarketRiskInterpretationArtifact",
    "MarketRiskInterpretationEngine",
    "MarketRiskInterpretationResult",
    "MarketRiskInterpretationStore",
    "MarketRiskInterpretationValidationError",
    "TACTICAL_LEAGUE_PROFILE_ARTIFACT_KIND",
    "TACTICAL_LEAGUE_PROFILE_CONTRACT_VERSION",
    "TACTICAL_LEAGUE_PROFILE_GENERATOR_VERSION",
    "TACTICAL_LEAGUE_PROFILE_MAPPING_REGISTRY_VERSION",
    "TacticalLeagueProfileArtifact",
    "TacticalLeagueProfileEngine",
    "TacticalLeagueProfileStore",
    "TacticalLeagueProfileValidationError",
]
